### ISSUE TITLE
Unable to recover a backup wallet in Dropbox

### ISSUE THREAD

**Issue by lra** [hivewallet/hive-mac#298]
I setup Hive to backup my wallet in Dropbox.
Then I launched Hive on a second computer, hoping I'd be able to import my wallet from Dropbox, but I couldn't, only on the command line doing:

``` bash
cp -Rv Dropbox/Hive-179Da/* Library/Application\ Support/Hive/
```

Is there a better way to do it ? Or is it still work in progress ?
Thanks

**Comment by iancrowther** [comment]
I copied my backup as instructed and I logged in (no welcome). I have a new btc address, is this correct?

my balance is 0.00 when i had a few £ remaining, is this just a sync delay?
