### ISSUE TITLE
Add Hive social media stuff to end of Wizard flow

### ISSUE THREAD

**Issue by w-hive** [hivewallet/hive-mac#389]
"Follow us on Twitter" / "Add us on Facebook" etc

Let's make the last wizard slide this stuff, with the wizard slide clearly indicating that they can get support there.

@mattatgit @haustraliaer

**Comment by jsuder** [comment]
![screen shot 2015-02-22 at 21 11 05](https://cloud.githubusercontent.com/assets/28465/6320206/9789a5b0-bad8-11e4-81a1-6c11e2bf61eb.png)

![screen shot 2015-02-22 at 21 16 59](https://cloud.githubusercontent.com/assets/28465/6320207/978a7ab2-bad8-11e4-8b7e-d0127348c3c3.png)
