### ISSUE TITLE
Hive iOS - "Woops! Request timeout."

### ISSUE THREAD

**Issue by Zabuza825** [hivewallet/hive-mac#476]
So, I've had this issue for months now and now it's getting ridiculous.

When I first got the HIVE iOS app it worked perfectly, but since 3-4 months ago I've been having this issue where if I try to access my LTC wallet I get a "Woops! Request timeout." error and it won't let me access my LTC wallet. I can access the wallet, but only after about 20 different attempts at accessing the wallet.

I can access the BTC side with zero issues, it is only the LTC wallet that is giving me this issue.

It is not the Internet connection as I have tried this on about 5 different networks, some of which I know are alright, and I still get this issue.

I have tried reinstalling the app and I still get this issue.

I have even since replaced the iPhone (my old phone was breaking down anyway) and I STILL GET THE ISSUE.

Is there any way to fix this? It's getting really annoying and if I can't fix it I may even switch over to a different wallet.

**Comment by w-hive** [comment]
Hey, sorry to hear that. Can you post a screenshot of the error message here please?

**Comment by w-hive** [comment]
Hi there, sorry to hear that, can you please re-post this issue with a screenshot over here:

https://github.com/hivewallet/hive-ios/issues

This is the issues area for the Mac version of Hive.
