### ISSUE TITLE
I cannot transfer my bit coins out of my Hive wallet 

### ISSUE THREAD

**Issue by grayble** [hivewallet/hive-mac#478]
I have had bit coins trapped in Hive for several weeks now. Whenever I try to send them elsewhere I get a message saying that I am not connected to the internet and I have the option to raise an error report. Whenever I raise an error report I get an automated acknowledgment. Other than that I get no response. Nothing.
I am on a Mac.
I may well have done something stupid but I don't know what. It was easy enough to transfer the bitcoin into Hive but I cannot get it out. Please can someone help me. I don't know where to turn

**Comment by mackuba** [comment]
Hmm, what error report? There shouldn't be any button for sending error report when you have no connection, you should only see a red bar at the top of the window... Can you send me a screenshot?

**Comment by grayble** [comment]
Hi Kuba, thanks, I've just emailed it to you.

**Comment by mackuba** [comment]
Where? I didn't get anything... Please send to kuba@hivewallet.com or upload here.

**Comment by grayble** [comment]
<img width="860" alt="screen shot 2015-07-22 at 22 08 02" src="https://cloud.githubusercontent.com/assets/13157024/8843879/7211fdd8-3106-11e5-8e2e-af7203336a88.png">

**Comment by mackuba** [comment]
This is not the Hive Mac app, Hive Mac looks like this: https://github.com/hivewallet/hive-mac#hive

You're using Hive Web. Please add a ticket here instead: https://github.com/hivewallet/hive-js/issues
