### ISSUE TITLE
Pending transactions

### ISSUE THREAD

**Issue by michelem09** [hivewallet/hive-mac#480]
Hello,
I saw only now you are unmantaining this app anymore, I'm trying to send my bitcoins to another wallet but all the transactions remain in pending status. How can I transfer my bitcoins?

**Comment by michelem09** [comment]
Oh sorry it seems one transaction is gone now.

**Comment by mackuba** [comment]
If you (or anyone) has such problems in future, I've added some troubleshooting tips recently to the FAQ, so this could help: https://github.com/hivewallet/hive-mac/wiki/FAQ#common-problems-and-known-issues
