### ISSUE TITLE
Importing old wallet

### ISSUE THREAD

**Issue by oskarkrawczyk** [hivewallet/hive-mac#483]
I'm aware that the project is no longer maintained, but perhaps someone could answer a quick question.

I've used Hive once or twice, in 2014, just sent my BTC to it and left it sitting on my disk.

Today tried to import the wallet, which is read correctly by v1.5, the odd thing is that I see the single transaction I've made in 2014 - which is recieving BTC. But the wallet appears to be empty.

Is it possible that the exported Dropbox backup simply didn't include the BTC?

**Comment by oskarkrawczyk** [comment]
Downgraded to an old version and it worked.

Carry on.

**Comment by mackuba** [comment]
The transaction list shown in the app sometimes gets out of sync with reality, due to poor error handling in some scenarios... Some kind of resync usually fixes this one way or another, more info in the FAQ: https://github.com/hivewallet/hive-mac/wiki/FAQ#common-problems-and-known-issues.
